[package]
name = "cargo-lambda-invoke"
description = "Cargo subcommand to work with AWS Lambda"
version = "0.8.0"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/cargo-lambda/cargo-lambda"
repository = "https://github.com/cargo-lambda/cargo-lambda"
keywords = ["cargo", "subcommand", "aws", "lambda"]
rust-version = "1.59.0"

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.
[dependencies]
cargo-lambda-remote = { version = "0.8.0", path = "../cargo-lambda-remote" }
clap = { version = "3.1.18", features = ["derive"] }
home = "0.5.3"
miette = "4.7.1"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.81"
strum = "0.24.0"
strum_macros = "0.24.0"
