[package]
name = "cargo-lambda-watch"
readme = "README.md"
rust-version.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
description.workspace = true

# Use cargo-edit(https://github.com/killercup/cargo-edit#installation)
# to manage dependencies.
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.
[dependencies]
aws_lambda_events = { version = "0.6.3", features = ["apigw"] }
axum = "0.5.4"
base64 = "0.13.0"
cargo-lambda-invoke.workspace = true
cargo-lambda-metadata.workspace = true
chrono = "0.4.19"
clap.workspace = true
dunce.workspace = true
http-api-problem = { version = "0.51.0", features = ["api-error", "hyper"] }
hyper = "0.14.18"
ignore-files = "=1.0.1"
miette.workspace = true
opentelemetry = "0.17.0"
opentelemetry-aws = "0.5.0"
query_map = { version = "^0.5", features = ["url-query"] }
reqwest.workspace = true
serde_json.workspace = true
tempfile = "3.3.0"
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tokio-graceful-shutdown = "0.5.0"
tower-http = { version = "0.3.3", features = [
    "catch-panic",
    "request-id",
    "trace",
    "cors",
] }
tracing.workspace = true
tracing-opentelemetry = "0.17.2"
tracing-subscriber.workspace = true
watchexec = "=2.0.2"
watchexec-filterer-ignore = "1.0.0"
