on: [push, pull_request]

name: Build

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  unit-tests:
    name: Unit Test Suite -- ${{ matrix.rust_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust_version: ["1.59.0", "stable"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust_version }}
          override: true
      - uses: Swatinem/rust-cache@v1

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  integration-tests:
    name: Integration Test Suite -- ${{ matrix.rust_version }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - name: macos-latest
            type: macos
            extension: .tar.xz
          - name: ubuntu-latest
            type: linux
            extension: .tar.xz
          - name: windows-latest
            type: windows
            extension: .zip
        rust_version: ["1.59.0", "stable"]
        zig_version: "0.0.9"
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"
      CARGO_ZIGBUILD_ZIG_PATH: "~/.npm-global/bin/zig"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Zig
        shell: bash
        run: |
          mkdir -p ~/ziglang
          curl -fsSL https://ziglang.org/builds/zig-${{ matrix.os.type }}-x86_64-${{ zig_version }}.${{ extension }} | tar xJ -C ~/ziglang
          echo "$HOME/ziglang" >> $GITHUB_PATH
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust_version }}
          override: true
      - uses: Swatinem/rust-cache@v1

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test simple example
        shell: bash
        run: |
          cd test/fixtures/single-binary-package
          ../../../target/debug/cargo-lambda lambda build --target-dir ../../../target
          ../../../target/debug/cargo-lambda lambda build --target-dir ../../../target --arm64

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings
