name: Build Crates

on:
  pull_request:
    paths:
      - 'crates/**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'deny.toml'
      - 'rustfmt.toml'
      - '.github/workflows/build.yml'

  push:
    branches: [ 'main' ]
    tags-ignore: [ '*' ]
    paths:
      - 'crates/**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'deny.toml'
      - 'rustfmt.toml'
      - '.github/workflows/build.yml'

  workflow_dispatch:

env:
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11.0

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: cargo-lambda
          shared-key: ${{ matrix.os }}

      - name: Run cargo test
        run: cargo test --all-features
